spring:
  application.name: HighConcurrencyLike
  mvc:
    servlet:
      path: /api
  profiles:
    active: local
  # DataSource Config
  datasource:
    url: jdbc:mysql://192.168.147.130:4000/thumb_db
    username: root
    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/thumb_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456

  data:
    # Redis 配置
    redis:
      database: 3
      host: 127.0.0.1
      timeout: 5000
      port: 6379
  pulsar:
    client:
      service-url: pulsar://192.168.147.130:6650
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 9199
# 整合 Prometheus + Grafana
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.75, 0.9, 0.95, 0.99